### ISSUE TITLE
DDR Best Hits not working

### ISSUE THREAD

**Issue by M4x1mumReZ** [alex-free/tonyhax#10]
**tonyhax version**: v1.1.2i
**Game name**: Dance Dance Revolution - Best Hits (Japan)
**Game code**: "SLPM-86693"
**Executable hash**: BIN file (SHA-1): 1b6ac32c66ff6f12877c53b7b2075f1ac01a9171 | Main executable (SHA-1): b51e0ab6448ee2f3afdf76c971b1520cdc98fe16
**Triggered at**: When selecting a game mode from the main menu, it locks up at the "Now Loading" screen.
**Is the console chipped?**: No
**Is it an original disc or a burned copy?**: Burned onto a Verbatim CD-R using a Plextor PlexWriter PX-W4012TA at 4x speed.

**Comment by M4x1mumReZ** [comment]
This has probably something to do with its anti-piracy measures. Patching the game with "APrip" or using cheat codes didn't resolve the problem.

**Comment by alex-free** [comment]
APrip methods do work fine with this game, it looks like it's broken in some other way.  Going to try to reproduce this with O.G. Tonyhax.

**Comment by M4x1mumReZ** [comment]
@alex-free You tried the same way with the swap trick also?

**Comment by alex-free** [comment]
> @alex-free You tried the same way with the swap trick also?

Yes this is an issue in the official Tonyhax that Tonyhax International has inherited.

**Comment by M4x1mumReZ** [comment]
Closed because the issue has been fixed in the latest version.

**Comment by alex-free** [comment]
> Closed because the issue has been fixed in the latest version.

No it has not?

**Comment by M4x1mumReZ** [comment]
> > Closed because the issue has been fixed in the latest version.
> 
> No it has not?

How come that this is the case?

**Comment by alex-free** [comment]
> > > Closed because the issue has been fixed in the latest version.
> > 
> > 
> > No it has not?
> 
> How come that this is the case? Thought the latest has the patches already implemented.

The issue with this game is not anti-piracy related, as it is broken in both the original tonyhax and international. I am not implementing a bypass until the underlying compatibility boot issue is fixed in the tonyhax upstream. I have no idea what your referring to in regards to patching or this being fixed.

**Comment by M4x1mumReZ** [comment]
> > > > Closed because the issue has been fixed in the latest version.
> > > 
> > > 
> > > No it has not?
> > 
> > 
> > How come that this is the case? Thought the latest has the patches already implemented.
> 
> The issue with this game is not anti-piracy related. This game has a booting issue in the original tonyhax as well. I am waiting for socram8888 to provide a fix.
> 
> I am not implementing an anti-piracy bypass until the underlying issue is resolved.
> 
> I have not added any patching or referenced this game in any update so far. This game is still in the known incompatible games section of the documentation

This booting issue does also happen when I perform the disc swap as well.

**Comment by M4x1mumReZ** [comment]
Solved https://github.com/socram8888/tonyhax/issues/121#issuecomment-1341365357
