### ISSUE TITLE
Suggestion for "CD-R Media For PSX Backups" section of readme.md

### ISSUE THREAD

**Issue by XxTriviumxX** [alex-free/tonyhax#30]
Hey!  I want to suggest another high quality cd-r to burn games: The good ol' Taiyo Yuden discs! They are rebranded as CMC Pro. I had less duds with them than Datalifeplus discs. In Canada, we can buy 100 Datalifeplus discs for 76CAD$ plus tax OR 100 CMC Pro for 62.19CAD$. Since they come from the United States, we don't need to pay a "levy of 0.29CAD$ per disc as required by the CPCC" or any taxes. The 62.19CAD$ includes the customs fee.... which means CMC Pro are much cheaper than datalifeplus in Canada! Before saying "It's made by CMC, which means they suck", keep in mind that both Datalifeplus and CMC Pro discs are made by CMC and that Datalifeplus are made in China and CMC Pro are made in Taiwan.

```
cdrecord -atip
```

result:

```
ATIP info from disk:
  Indicated writing power: 4
Disk Is not unrestricted
Disk Is not erasable
  Disk sub type: Medium Type A, high Beta category (A+) (3)
  ATIP start of lead in:  -11849 (97:24/01)
  ATIP start of lead out: 359847 (79:59/72)
Disk type:    Long strategy type (Cyanine, AZO or similar)
Manuf. index: 25
Manufacturer: Taiyo Yuden Company Limited
```

datalifeplus: https://www.amazon.ca/dp/B002OOWC9C?psc=1&ref=ppx_yo2ov_dt_b_product_details

cmc pro: https://www.amazon.ca/dp/B01HFBO78W?psc=1&ref=ppx_yo2ov_dt_b_product_details

edit: added "CAD" to all dollar signs

**Comment by XxTriviumxX** [comment]
I forgot to add that i read somewhere that playstation discs were made with taiyo yuden discs. I don't know if that info is correct though.

**Comment by alex-free** [comment]
I don't think CMC makes DataLifePlus, my DataLifePlus lists:

Manufacturer: Mitsubishi Chemical Corporation

and my UltraLife Gold Archival Grade lists:
 Manufacturer: TDK Corporation

The standard shitty Verbatim CD-Rs that you find at Wallmart are do have CMC Magenetics as the manufacturer.

I will add these info though, really good work.

**Comment by XxTriviumxX** [comment]
taken from https://wl.vern.cc/wiki/Verbatim_(brand)?lang=en#Key_dates: 

2020: CMC acquires Verbatim/Mitsubishi Kagaku Media.

The atip is still saying "Mitsubishi Chemical Corporation", just like the cmc pro atip saying "Taiyo Yuden Company Limited". The reason here is that BOTH cmc plus and datalifeplus use the SAME equipment and the SAME strict regulations to make them. They didn't change the atip at all. CMC make CMC Pro using the same equipment and stict regulations as Taiyo Yuden/JVC before they got sold to CMC in 2015. Same goes for datalifeplus, they are made by CMC since 2020 using the same equipment and the same strict regulations as the old verbatim factory before 2020.

As per which is more reliable?

I've seen many failed burned datalifeplus discs that had weird "dye swirls". I've seen none with CMC pro discs. Maybe it's because datalifeplus discs are made in china and CMC pro are made in taiwan.  I'd say, made in china discs < made in taiwan discs.

**Comment by XxTriviumxX** [comment]
you made a mistake/typo here for the UltraLife Archival Grade Gold CD-R discs:

> Here is the ATIP information displayed by cdrecord -atip for a Verbatim DataLifePlus CD-R:

```
ATIP info from disk:
  Indicated writing power: 5
Disk Is not unrestricted
Disk Is not erasable
  Disk sub type: Medium Type B, low Beta category (B-) (4)
  ATIP start of lead in:  -12520 (97:15/05)
  ATIP start of lead out: 359849 (79:59/74)
Disk type:    Short strategy type (Phthalocyanine or similar)
Manuf. index: 26
Manufacturer: TDK Corporation
```

replace "datalifeplus" with "UltraLife Archival Grade Gold CD-R"

**Comment by alex-free** [comment]
> you made a mistake/typo here for the UltraLife Archival Grade Gold CD-R discs section:
> 
> 
> 
> > Here is the ATIP information displayed by cdrecord -atip for a Verbatim DataLifePlus CD-R:
> 
> 
> 
> ```
> 
> ATIP info from disk:
> 
>   Indicated writing power: 5
> 
> Disk Is not unrestricted
> 
> Disk Is not erasable
> 
>   Disk sub type: Medium Type B, low Beta category (B-) (4)
> 
>   ATIP start of lead in:  -12520 (97:15/05)
> 
>   ATIP start of lead out: 359849 (79:59/74)
> 
> Disk type:    Short strategy type (Phthalocyanine or similar)
> 
> Manuf. index: 26
> 
> Manufacturer: TDK Corporation
> 
> ```
> 
> 
> 
> replace "datalifeplus" with "UltraLife Archival Grade Gold CD-R"

Yes your absolutely correct, I've actually already fixed it in my local build of v1.3.4. I'm waiting on some test results but the final version of v1.3.4 will include your additions to the documentation which again is greatly appreciated, you've kept up with these monopolies more then I have lol

**Comment by alex-free** [comment]
I will say

Hands down 
For $$$ isn't as problem 
74min DataLifePlus Verbatim CD-Rs are the ultimate media for PSX. Copyright 97 or 99 on the cd label at the back of each cd case...

**Comment by XxTriviumxX** [comment]
i bet they are the ultimate cd-r to get LOL. kinda like chasing after japan-made taiyo yudens. $$$$$$$$$

**Comment by alex-free** [comment]
> i bet they are the ultimate cd-r to get LOL. they must be expensive..kinda like chasing after japan-made taiyo yudens. $$$$$$$$$

They are not stupid expensive, they are still on eBay quite a bit, but compared to just buying a 50 CDR spindle they really are a rich man's product lol.

![image](https://github.com/alex-free/tonyhax/assets/72545918/4c391a97-e604-4b26-9128-defd62277bee)

![image](https://github.com/alex-free/tonyhax/assets/72545918/03d4d26c-5b8b-4c46-ab7c-7e2fa3bf8af0)

I did buy a ton of these last year and always had excellent results. The trick is to search for '74min DataLifePlus' on eBay and to find the copyright date of 97 or 99 on the back like in the images above.

Believe it or not the DataLifePlus gimmick does seem real. I never had a dud burning literally 24-26 year old new old stock sealed discs.

**Comment by JMaxxL** [comment]
Am I having bad burns with castlevania SON or is it possible its a copy protection issue, I noticed when I loaded a crap load of gameshark code in [190] audio issues actually got worse? I cant tell because some of the problem go away when I run the SON off of my 7501 which has basically a perfect laser (it sat in a closet for 20 years & was only used THIS YEAR) but it still skips this is the 4th burn of SON that has had issues anyone else report problems with castlevania SON

**Comment by alex-free** [comment]
> Am I having bad burns with castlevania SON or is it possible its a copy protection issue, I noticed when I loaded a crap load of gameshark code in [190] audio issues actually got worse? I cant tell because some of the problem go away when I run the SON off of my 7501 which has basically a perfect laser (it sat in a closet for 20 years & was only used THIS YEAR) but it still skips this is the 4th burn of SON that has had issues anyone else report problems with castlevania SON

If the 7501 is not having any problems with the same codes it's just your psone cd drive.

No copy protection in SOTN, I've even played it a bit. That's mottzilla's favorite game.

Maybe you might want to refurb the psone cd drive with my guide? It's probably the drive lubrication not the laser itself.

**Comment by alex-free** [comment]
Send the codes I think I have a SOTN disc still I'll see if there's any issues

**Comment by alex-free** [comment]
> this may be because of the 190 codes.... my burned symphony of the night backup plays like a champ

@JMaxxL 

That is an insane amount of codes. The hard limit is something like 255 at once but I never tested more then like 140 (which did work all at the same time correctly).

If you don't have any audio issues without the codes, it's the codes (also maybe they can conflict with each other? what happens with the GameShark Lite, emulators like DuckStation using native cheat function support, etc.?)

If you still have audio issues without the codes, then it's the console (IIRC SOTN streams XA audio which is really hard for the PSX to do with 80min discs/CD-Rs to begin with, and if your cd drive isn't in tip top shape it can cut out.

If you send the txt, I could see if the audio cuts out on my Japanese PS2 via International to rule everything out.

**Comment by alex-free** [comment]
Added in v1.3.4

**Comment by XxTriviumxX** [comment]
I checked the 74min DataLifePlus Verbatim CD-R with the Copyrights of 97 or 99.  The speeds are up to 8x, which is *maybe* impossible to burn with a recent burner. May be worth including.

**Comment by alex-free** [comment]
> I checked the 74min DataLifePlus Verbatim CD-R with the Copyrights of 97 or 99.  The speeds are up to 8x, which is *maybe* impossible to burn with a recent burner. May be worth including.

Burns correctly @10x with my external usb DVD burner. I'm pretty sure any multiple of 2 is fine past 8x for them. I don't burn any higher then 10x with this burner though because it's the slowest it will go and I've had discs which are unreadable if burned at 16x (though they were not the specific 90s verbatim DataLifePlus discs, they were the modern 80min ones from 2022).

**Comment by XxTriviumxX** [comment]
ive had many bad burns with datalifeplus at 16x which is the minimum speed with my drive. I've had NONE with cmc pros at 16x. Almost all of the games i've burned with CMC Pros were at full speed (AWS speed in imgburn). However, the JRPG games such as final fantasy games, chrono cross and legend of dragoon needed a 16x burn for cinematics. I'm pretty sure it's my drive that didn't get along with datalifeplus or that i landed on a very rare bad batch. Both recent datalifeplus and CMC pro can burn over 32x.

As for the old 90's datalifeplus, they are limited at 8x as seen on the pictures above.  So burning them at 10x probly won't work... unless you tested them! I would be very tempted to buy some if they work at 16x LOL

**Comment by XxTriviumxX** [comment]
i've contacted socram8888 and pointed out your CD-R section. Asked him to include it to his orca.pet/tonyhax page with your name as reference. Newcomers will have the right discs right away. What do you think?

**Comment by socram8888** [comment]
Personally I've burnt circa 50 the cheapest 80 minutes CD-Rs from Verbatim and Philips that I could find in local retail stores, using a shitty external Asus USB burner for testing multiple games and bugs, and never had any issues with any of them on my SCPH-102. Not even a singular toast.

I could certainly include a warning about burning as slow as possible, as that's something I'd always recommend doing in general. However, regarding media type, I'm not sure I want users to be super concerned about getting a particular media when I've not found any reason to prefer any over the other.

**Comment by alex-free** [comment]
> Personally I've burnt circa 50 the cheapest 80 minutes CD-Rs from Verbatim and Philips that I could find in local retail stores, using a shitty external Asus USB burner for testing multiple games and bugs, and never had any issues with any of them on my SCPH-102. Not even a singular toast.
> 
> 
> 
> I could certainly include a warning about burning as slow as possible, as that's something I'd always recommend doing in general. However, regarding media type, I'm not sure I want users to be super concerned about getting a particular media when I've not found any reason to prefer any over the other.

The PSones all have the best CD controller version, VC3 (which is shared with the last fat 7XXXX and 9XXXX models as well). Also the best CD drives.

Older models seem to be much more picky, and especially about the 74min v.s. 80min thing.

If a drive is starting to fail or have issues it's even more apparent.

I've personally always had terrible results with specific media, in particular the maxell CD-Rs are garbage, even on the Dreamcast.

https://gbatemp.net/threads/do-modern-burners-cds-make-lower-quality-ps1-backups.628708/

**Comment by XxTriviumxX** [comment]
One could suggest using the datalifeplus/CMC PRO/UltraLife Archival Grade Gold discs.... While not warning future users not to use cheaper discs.

**Comment by XxTriviumxX** [comment]
i made the mistake of buying 50 maxel music cds when i discovered tonyhax on orca.pet/tonyhax.  I really wished i fell on this github repo and buy good cds right away.

**Comment by alex-free** [comment]
> i made the mistake of buying 50 maxel music cds when i discovered tonyhax on orca.pet/tonyhax.  I really wished i fell on this github repo and buy good cds right away.   sh**ty burns galore.

It's a rite of passage 😂

**Comment by alex-free** [comment]
@XxTriviumxX bravo, bravo. I think Verbatim DataLifePlus CD-Rs have been discontinued? The buy button no longer exists at 

https://www.verbatim.com/prod/optical-media/cd/compact-disc-recordable/cd-r-silver-inkjet-printable/

for some time. I decided to take a chance and got 100 CMC Pro 80min discs. These may be the best CD-Rs (at least for sure 80 minute ones) I've ever used! They work amazingly well on my USA 1001 and 1000 Japan launch PSXs.

**Comment by XxTriviumxX** [comment]
That's great! I did not have a single bad burn with them. I could easily burn on a CMC pro without verifying it. I got bad burns because of bad images... other than that they were flawless. I've had many bad burns with datalifeplus... some of them had "dye swirls" after a bad burn.

By the way, your url points to a 10x non-datalifeplus discs box

**Comment by XxTriviumxX** [comment]
also... i sometimes would get "Write Speed Miscompare" errors while burning at the lowst available speed (16x) with datalifeplus. It NEVER happened once with CMC Pros at 16x.

**Comment by alex-free** [comment]
> also... i sometimes would get "Write Speed Miscompare" errors while burning at the lowst available speed (16x) with datalifeplus. It NEVER happened once with CMC Pros at 16x.

https://www.verbatim.com/prod/optical-media/cd/compact-disc-recordable/cd-r-silver-inkjet-printable-sku-95256/ is the 100 spindle. Again, no buy button. It did use to exist a few months ago, I used to buy them directly from the website.

We have the CMC Pros though so it doesn't matter. I've been burning at 10x and my consoles are happy.

**Comment by XxTriviumxX** [comment]
hi! i dont know how else i can contact you @alex-free and i feel this issue was related to my question.
You made a guide about cd and cd burners. I have this USB/IDE adapter that provides proper 4 pin electricity:
![image](https://github.com/user-attachments/assets/571855fc-3b9c-4442-963d-8a1b6b938f84)
Is these safe to use with IDE burners? I'm asking because I don't have the motivation to get a windows 98/xp pc...

**Comment by alex-free** [comment]
> hi! i dont know how else i can contact you @alex-free and i feel this issue was related to my question.
> 
> You made a guide about cd and cd burners. I have this USB/IDE adapter that provides proper 4 pin electricity (the 4pin is not in the picture)
> 
> ![image](https://github.com/user-attachments/assets/571855fc-3b9c-4442-963d-8a1b6b938f84)
> 
> Is this safe to use with IDE burners? Works great with IDE hdds. 
> 
> I'm asking because I don't have the motivation to get a windows 98/xp pc...

I use a very similar adapter, a Plextor-PX-708A, and a gaming laptop on Linux personally. Should work.

**Comment by XxTriviumxX** [comment]
> on Linux

Do you recommend brasero?

**Comment by alex-free** [comment]
> > on Linux
> 
> 
> 
> Do you recommend brasero?

No, use an up to date cdrdao https://github.com/alex-free/cdrdao-pled

Or better yet https://github.com/alex-free/playstation-disc-burner
