### ISSUE TITLE
Crash Bash USA triggers the anti piracy screen

### ISSUE THREAD

**Issue by pcortesduoc** [alex-free/tonyhax#4]
**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.

- v1.1.2

**Game name**: Self-describing

- Crash Bash (NTSC-U)

**Game code**: Game's serial number, eg "SCES-12345"

- SCUS-94570

**Executable hash**: SHA-1, SHA-256 or MD-5 of the game's main executable or the disc. This is important since there could be multiple revisions of the same game.

- SHA-1 of the bin file: fce2d66a12d49ec50aa1b93e138da6c6f646eb16
- SHA-1 of the cue file: b0a092b40ec337a1098fe99fa1357c7bdd164498

**Triggered at**: Please explain when is the screen shown, eg "after the Sony logo", or "after the first video"

- Shortly after the game boots up

**Is the console chipped?**: Yes or no.

- No

**Is it an original disc or a burned copy?**: Self-explaining.

- Burned

**Comment by M4x1mumReZ** [comment]
It doesn't seem to have a problem with me running under the latest "Tonyhax International" build - used both the boot CD and cartridge versions, and everything turned out perfectly fine with not a single anti-piracy message in sight. "Tonyhax International" only seems to have a problem with APv2 titles in question, as this form of anti-piracy has an additional measure in place that not only does it constantly check for the modchip spamming the 'SCEX' string, but also to see if a swap trick was performed.

**Comment by M4x1mumReZ** [comment]
Try using different CD-R media and/or another console - I was using a Verbatim 700MB CD-R and a SCPH-7502 model for this test. If the problems still persist, then you could ask "Alex" to add AP patches for that game.

**Comment by alex-free** [comment]
Hmm, I think @M4x1mumReZ was using the PAL version of Crash Bash which may not contain the anti-piracy checks. Some games don't have the anti-piracy check code enabled in all regional versions of the game. The USA version I believe does contain the checks, and I haven't added support yet for this game specifically to bypass those. I'll look into adding support for Crash Bash. Thanks for the report.

**Comment by M4x1mumReZ** [comment]
I'm using the USA version as the person specified.

**Comment by M4x1mumReZ** [comment]
The PAL version on the other hand uses LibCrypt which is a completely different thing.

**Comment by M4x1mumReZ** [comment]
@M4x1mumReZ It usually shows up immediately at the SCEA screen. I played the game thoroughly and I didn't see it appear.

**Comment by alex-free** [comment]
Alright @pcortesduoc I can confirm that the AP prohibited screen apears right after SCEA presents screen on my stock SCPH-1001 using the latest Tonyhax International v1.1.2 Boot CD. Not sure why @M4x1mumReZ can not reproduce...

I'm going to see if the latest pull request from @M4x1mumReZ however fixes it.

**Comment by alex-free** [comment]
@pcortesduoc I just tested this beta build of Tonyhax International and it bypasses the screen on my stock SCPH-1001 console! Let me know if this solves your issue so I can close this.
[tonyhax-v1.1.3-BETA-TEST-international.zip](https://github.com/alex-free/tonyhax/files/10044846/tonyhax-v1.1.3-BETA-TEST-international.zip)

**Comment by M4x1mumReZ** [comment]
If it works for you, then it will 100% work for the other person that's for sure.

**Comment by pcortesduoc** [comment]
Yep I can confirm it does work. Thank you very much, both of you :)

**Comment by M4x1mumReZ** [comment]
No problem @pcortesduoc

**Comment by M4x1mumReZ** [comment]
If you have any other issues, just let us know for sure. ;)
