### ISSUE TITLE
King's Field (SLPS-00017)

### ISSUE THREAD

**Issue by StevtheRPGGuy** [alex-free/tonyhax#43]
I'm using a PlayStation 2 model SCPH-39001 with Tonyhax International v1.4.1, and when trying to play an original copy of King's Field (Japan), it freezes at the "Starting" message. I am using the NTSC-U/C version of Crash Bandicoot: Warped as my entrypoint, and I copied the raw memory card saves over using uLaunchELF. Tonyhax International reports the BIOS version as 5.0 02/07/02 A.

**Comment by alex-free** [comment]
> I'm using a PlayStation 2 model SCPH-39001 with Tonyhax International v1.4.1, and when trying to play an original copy of King's Field (Japan), it freezes at the "Starting" message. I am using the NTSC-U/C version of Crash Bandicoot: Warped as my entrypoint, and I copied the raw memory card saves over using uLaunchELF. Tonyhax International reports the BIOS version as 5.0 02/07/02 A.

Interesting, issue confirmed even with DuckStation emulator. This effects both original Tonyhax and Tonyhax International. I'll look into it, thanks for reporting this.

**Comment by alex-free** [comment]
I have confirmed that King's Field USA does not have this issue and works fine (in emulation at least, should also be fine on console): http://redump.org/disc/94/

This still needs to be addressed however for the original Japanese release because this is a bug.

**Comment by alex-free** [comment]
I think the issue has been identified so hang in there :)

**Comment by StevtheRPGGuy** [comment]
I think it is worth noting that the American King's Field is actually King's Field II in Japan, and US King's Field II is JP King's Field III.

**Comment by alex-free** [comment]
> I think it is worth noting that the American King's Field is actually King's Field II in Japan, and US King's Field II is JP King's Field III.

Okay that does make some sense in a way, thanks.

**Comment by alex-free** [comment]
How playable is this without knowing japanese? Looks interesting once we get this working I might want to try this out

**Comment by StevtheRPGGuy** [comment]
It does require you to know Japanese. Luckily, there is a translation patch out there.

**Comment by alex-free** [comment]
> It does require you to know Japanese. Luckily, there is a translation patch out there.

I did see some japanese heavy menus. That is good to know about the patch since I'm a sucker for these early 90s games like this one. Can't wait to get this working.

**Comment by alex-free** [comment]
@StevtheRPGGuy I have a fix that works, right now it is a patch to the disc image does that work for you? I want to get International working with the original disc but this does work and issue identified.

**Comment by alex-free** [comment]
Wait actually I can do this with International easily, you'll be able to use your original japanese PSX disc I'll send over a beta version of International v1.4.2

**Comment by alex-free** [comment]
@StevtheRPGGuy  okay haven't got the chance to try it on real hardware but on emulation this beta version is working, should work for you now:
[tonyhax-international-v1.4.2b1.zip](https://github.com/alex-free/tonyhax/files/12776635/tonyhax-international-v1.4.2b1.zip)

**Comment by StevtheRPGGuy** [comment]
From my testing, everything seems to be fine.

**Comment by alex-free** [comment]
@StevtheRPGGuy did you test the English patch by chance? I do actually want to play this game now.

**Comment by StevtheRPGGuy** [comment]
I have now tested the English patch, and everything seems to work as intended using a good quality CD-R.
