### ISSUE TITLE
"NEEDED GAMES"

### ISSUE THREAD

**Issue by JukePlz** [alex-free/tonyhax#47]
Both Silent Hill (Rev 2) and Panekit: Infinitive Crafting Toy Case Japan (Rev 1) that are requested in [this page](https://alex-free.github.io/tonyhax-international/anti-piracy-bypass.html#needed-games) can be found at [this archive.org collection](https://archive.org/download/chd_psx_jap/CHD-PSX-JAP/).

I've verified that they match the Redump database and validate properly.

Sadly, the other two missing discs are not present. Well, Doko Demo Issho (demo 2) disc is [in the second part of the Japanese collection](https://archive.org/download/chd_psx_jap_p2/CHD-PSX-JAP/), but it seems to be a bad dump that doesn't validate against the Redump hash. Maybe still good enough to check how the copy protection works tho?

Cheers.

**Comment by alex-free** [comment]
Someone sent me all of the games and I was able to add support for the next update, I haven't pushed it out yet though. I very much appreciate you sending me these, but to avoid any DCMA issues I'll edit your issue. Thanks though!

**Comment by JukePlz** [comment]
Understood. The second link also points to the same place, so I will remove that one too.

Was going to message you directly, but Github doesn't seem to have DMs anymore and I couldn't find your email.
