### ISSUE TITLE
Metal Gear Solid: Integral Antipiracy

### ISSUE THREAD

**Issue by soulsnake** [alex-free/tonyhax#48]
**tonyhax version**: tonyhax version international version 1.4.5
**Game name**: Metal Gear Solid: Integral
**Game code**: SLPM-86470
**Executable hash**: Same as http://redump.org/disc/423/
SHA1: 16F6672456BAF5E6C46E1ABBA5CDC68EC124B633
SHA256: 9B4C110591CC11126168612CE646D74C94478EF1EBB508509FEB4FF0BB69A0E5
**Triggered at**: after selecting game difficulty (new game)
**Is it an original disc or a burned copy?**: Original

Tested on  SCPH-102, 4.4 (2000-03-24), PAL using FreePSXBoot loader (image for SCPH-102 4.4 slot 2).
Antipiracy triggered on Disc 1 and Disc 2. No issue with Disc 3 (Special Missions)
No issue with tonyhax normal version 1.4.5 (not international) FYI

**Comment by alex-free** [comment]
Fixed in version 1.4.6. thank you for the report!

**Comment by soulsnake** [comment]
Thank you for the fix. Tested with CD1 and now working ;)
