### ISSUE TITLE
Drastic skipping/loading issues on every laser i try on SCPH-100

### ISSUE THREAD

**Issue by Dorikururi** [alex-free/tonyhax#49]
**tonyhax version**: 1.4.6.
**Installation method**: Downloaded from the site and installed using MCA on a modded PS2.
**Entry point game**: Mainly Soul Edge & Minimoni but i've tried about 10 different games all give me the same issues.
**Console model**: SCPH-100 Japanese PS1, tested on 3 models with 5 laser assemblies and 3 kinds of CD-R media.
**Integrity check**: Yes. All games boot but barely load
**BIOS version**: 4.5 05/25/00 / J and 4.3 03/11.00 J
**Target game**: All games i've tried have this issue, i've been trying with Mega Man legends cause it opens with the FMV Capcom logo, . which almost always plays for half a second before it hangs and hangs on the now loading screen, when it does get past it dialogue skips heavily. Games like Klonoa and R4 hang on the Namco logo

**Bug explanation**:
Nothing initially seems wrong, but all issues happen as soon as a Backup from any region is booted into.

With all lasers, recordable CD-R media and 3 SCPH-100 consoles i've tried the games barely read they hang almost immediately, skip FMV's and hang on splash screens, typical bad laser behavior, however oddly taking these lasers with the same disc inserted to a PAL chipped PS1 or even a PAL PSone with no modchip booting through Tonyhax there are no issues. 

I don't think this is a known issue or am even sure if this is a Tonyhax problem as i can't find any other info on it, Likely due to the fact playing burned discs on these SCPH-100 models is kind of new, if this is in fact someting else feel free to close this problem, i would be interested in what it actually in that case.

Love the program thanks for making it! It's my favourite FreePSXboot tool, with 60hz forced output for Pal games it'd be 100% perfect.

Happy holidays!

Kevin.

**Comment by Dorikururi** [comment]
Also since posting this i've tried about 5 different disc brands and while some are better than others none get Mega Man Legends or Klonoa in game 99% of the time, whilst all these discs work fine with that same laser on an older Playstation.

**Comment by alex-free** [comment]
Especially since imports are having no issues, this appears to be an issue with the CD-R media/Burn Speed/CD Burner combination. Have you seen https://alex-free.github.io/tonyhax-international/#faq ? The SCPH-100 should have no issue compared to other models when using high quality media/burns/burner. What are you using at the moment?

Also double checking, you're removing the FreePSXBoot memory card after Tonyhax international starts right?

Curious why you'd want to force pal games to ntsc? I could make that optional on boot but the games would run too fast.

**Comment by Dorikururi** [comment]
I just read through your write-up on the difference in CD-R media and found it pretty enlightening! I never knew 74 minute discs were so much better than 80 minute ones, those are the ones i've been using so i guess i'll go looking for some 74 minute discs, my burner is nothing special, just a newish LG burner full size burner. My Discs are basically all newish 80minute discs under different brands but made by CMC Magnetics.

Would the burns being the problem not also mean the games should have the same skipping issues on other consoles? The same discs and lasers work fine on a PAL PSone console so that kind of ruled out the discs/lasers out in my mind, could it be the SCPH-100 just supplies less power to the laser or has worse error correction than the other models? 

It's a real headscratcher for me as there does seem to be way less room for error on lower quality burns on specifically this model, i've been using discs i've beat countless games on, beat that same back-up up MM legends with 0 problems just earlier this year on a SCPH-9002


Also yes i pull the Memory card when i swap the real Ntsc-J game for the backup usually. :)


As for a the Video mode forcing i think it'd be a great thing to have as there's a good handful of PAL games up til the HD era that were never optimized correctly, so instead of being tweaked to run at less frames and the correct speed for 50HZ they just let them play slow, when played in a forced 60hz they play just like the North American versions. (Sonic 1 on Mega Drive is probably the best example of this) it'd be cool as it could breathe some new life in games that suffer from this, some American games have PAL counterparts suffering from this whilst still being a lot cheaper, having the option to force those to 60hz would fix those discs right up. Lots of Pal software is like this which is why a way to force 60hz is always really nice. 

As a bonus it'd let you force a display on the PSone screen, the PAL versions only support 50hz and the NTSC versions only support 60hz, having an option to force 50hz or 60hz on boot would make the whole library playable on both screens which would be amazing!

**Comment by alex-free** [comment]
> I just read through your write-up on the difference in CD-R media and found it pretty enlightening! I never knew 74 minute discs were so much better than 80 minute ones, those are the ones i've been using so i guess i'll go looking for some 74 minute discs, my burner is nothing special, just a newish LG burner full size burner. My Discs are basically all newish 80minute discs under different brands but made by CMC Magnetics.
> 
> 
> 
> Would the burns being the problem not also mean the games should have the same skipping issues on other consoles? The same discs and lasers work fine on a PAL PSone console so that kind of ruled out the discs/lasers out in my mind, could it be the SCPH-100 just supplies less power to the laser or has worse error correction than the other models? 
> 
> 
> 
> It's a real headscratcher for me as there does seem to be way less room for error on lower quality burns on specifically this model, i've been using discs i've beat countless games on, beat that same back-up up MM legends with 0 problems just earlier this year on a SCPH-9002
> 
> 
> 
> 
> 
> Also yes i pull the Memory card when i swap the real Ntsc-J game for the backup usually. :)
> 
> 
> 
> 
> 
> As for a the Video mode forcing i think it'd be a great thing to have as there's a good handful of PAL games up til the HD era that were never optimized correctly, so instead of being tweaked to run at less frames and the correct speed for 50HZ they just let them play slow, when played in a forced 60hz they play just like the North American versions. (Sonic 1 on Mega Drive is probably the best example of this) it'd be cool as it could breathe some new life in games that suffer from this, some American games have PAL counterparts suffering from this whilst still being a lot cheaper, having the option to force those to 60hz would fix those discs right up. Lots of Pal software is like this which is why a way to force 60hz is always really nice. 
> 
> 
> 
> As a bonus it'd let you force a display on the PSone screen, the PAL versions only support 50hz and the NTSC versions only support 60hz, having an option to force 50hz or 60hz on boot would make the whole library playable on both screens which would be amazing! 
> 
> 
> 
> 
> 
> 
> 
> 

I can totally make keeping the video mode NTSC optional in the next update.

As for the mysterious poor results with the SCPH-100, I'm not sure but it could be that they are more sensitive to poor media and burners than other models. I don't have the SCPH-100 specifically to compare it to my others, but one thing you can try is to see how the disc read performance is with UniROM. If it is the same then we can rule out any issues with Tonyhax international. I am also curious what the CD BIOS line says in Tonyhax international for your console if you can provide that.

The CMC media and generic burner is most likely the problem. I had nothing but issues using a similar setup to what you have. Now I have amazing results with the Plextor PX 708A burner (using an IDE to USB adapter) and CMC Pro 80 minute discs (they are completely different from the other CMC made stuff because they use Taiyo yuden technology and manufacturing process), as well as old new stock 74 minute discs. Burn speed also matters a lot, experimentation is always best to find out the optimal setup for the combination of burner and cd-r media.

**Comment by Dorikururi** [comment]
That would rock!! Something like Hold L1 to force 50hz & R2 to force 60hz would make Tonyhax even more useful, would make completely stock PAL consoles be able to enjoy those unoptimised games in 60hz too! 

I've not tried Unirom on the SCPH-100 but i'll give it a shot and report back! 

The CD BIOS in Tonyhax seems to say C3010299 on a Newer model and C30603A1 on an older model, both have the same issues. Would you happen to know where that Bios is stored? it sounds like a difference in that bios might be what's causing the problem here, maybe swapping the chip it's on with one from another model would solve my problem entirely, i have a broken pal PSone i could get the chip from, unless it's integrated into the CPU or has some part of the region coding in it as well.

I'll definitely also try different media! gotta wait for the thrift stores to open back up here to go huntin' for some new old stock ones, they usually have loads, the ones online are insanely overpriced. Wanted to try an old IDE burner but my XP machine died on me so that's not really an option at the moment. 
As for experimentation with my current setup would burning faster be worth trying? Or would slower basically always be better? I'm up for trying anything but i also don't wanna waste discs if it's not worth doing lol.

**Comment by alex-free** [comment]
> That would rock!! Something like Hold L1 to force 50hz & R2 to force 60hz would make Tonyhax even more useful, would make completely stock PAL consoles be able to enjoy those unoptimised games in 60hz too!
> 
> I've not tried Unirom on the SCPH-100 but i'll give it a shot and report back!
> 
> The CD BIOS in Tonyhax seems to say C3010299 on a Newer model and C30603A1 on an older model, both have the same issues. Would you happen to know where that Bios is stored? it sounds like a difference in that bios might be what's causing the problem here, maybe swapping the chip it's on with one from another model would solve my problem entirely, i have a broken pal PSone i could get the chip from, unless it's integrated into the CPU or has some part of the region coding in it as well.
> 
> I'll definitely also try different media! gotta wait for the thrift stores to open back up here to go huntin' for some new old stock ones, they usually have loads, the ones online are insanely overpriced. Wanted to try an old IDE burner but my XP machine died on me so that's not really an option at the moment. As for experimentation with my current setup would burning faster be worth trying? Or would slower basically always be better? I'm up for trying anything but i also don't wanna waste discs if it's not worth doing lol.

Slower is not always better, depending on the CD-R media and burner. You may have better results with a different burn speed (i.e. 16x). 

You can get an IDE to USB adapter like I have and use an IDE burner on a laptop.

Don't worry about the CD BIOS needing to be replaced, that is not a problem I was just curious.

For 74 minute media, [theser](https://alex-free.github.io/psx-cdr/#tdk-data-cd-r-for-computer-writers-74-minute) are the cheapest I can find on ebay (and they work well) if you don't have great luck in stores.

Please test Unirom when you have the chance, so we know if there is a tonyhax international specific issue.

**Comment by Dorikururi** [comment]
Late reply, sorry, Holidays got in the way, Happy new year!

I got around to trying Unirom and it does indeed have the same issues so it's luckily not a problem with Tonyhax! So it was something to do with my media all along, guess that's something learnt in that Japanese PS1's are the pickiest consoles to play backups on. 

Wasn't able to find any good CD-r's yet, Thanks for the link! i'll definitely give those a shot if the other stores don't have any either, but i actually found some old backups on 74min discs in a box somewhere that i didn't even know i had! Those seem to work perfectly so they really do seem to be the ticket on PS1 games like you said.

Also managed to get some newer Ritek discs working through trying a different burner and burning at the fastest speed possible, did need to do a little pot tweaking PS1 side but basically everything seems to play now, thanks for the help and the amazing CD-R writeup again, fantastic source! 

Apologies for opening the ticket for something that ended up being an isolated issue, i hope some of the findings were good info though! And i look forward to the 50hz 60hz forcing in a future release of Tonyhax International, Unirom did actually have the same feature but it's a bit of a chore to use on Japanese PS1's, Tonyhax is way faster so i vastly prefer it, so i'm glad it's gonna be even better in the future!

I'll close the issue with this comment, Thanks again for the help getting this sorted out! :)

**Comment by Dorikururi** [comment]
Late reply, sorry, Holidays got in the way, Happy new year!

I got around to trying Unirom and it does indeed have the same issues so it's luckily not a problem with Tonyhax! So it was something to do with my media all along, guess that's something learnt in that Japanese PS1's are the pickiest consoles to play backups on.

Wasn't able to find any good CD-r's yet, Thanks for the link! i'll definitely give those a shot if the other stores don't have any either, but i actually found some old backups on 74min discs in a box somewhere that i didn't even know i had! Those seem to work perfectly so they really do seem to be the ticket on PS1 games like you said.

Also managed to get some newer Ritek discs working through trying a different burner and burning at the fastest speed possible, did need to do a little pot tweaking PS1 side but basically everything seems to play now, thanks for the help and the amazing CD-R writeup again, fantastic source!

Apologies for opening the ticket for something that ended up being an isolated issue, i hope some of the findings were good info though! And i look forward to the 50hz 60hz forcing in a future release of Tonyhax International, Unirom did actually have the same feature but it's a bit of a chore to use on Japanese PS1's, Tonyhax is way faster so i vastly prefer it, so i'm glad it's gonna be even better in the future!

I'll close the issue with this comment, Thanks again for the help getting this sorted out! :)
