### ISSUE TITLE
This Is Football/V-Rally: Championship Edition 2 - Libcrypt Protection Effects

### ISSUE THREAD

**Issue by aha360** [alex-free/tonyhax#58]
Hello there

I am not sure where to post this as this is my first time contributing to adding in information to a project here, but I would like to let you know that This Is Football's LibCrypt protection kicks in whenever you try to load in a game with two teams selected, whereby the loading bar gets stuck at approximately 80-85%.

Also, V-Rally: Championship Edition 2 has the same protection with similar effects where if you try to choose your car and game mode, the game will try to load, and then permanently gets stuck on the loading screen with the ECG patterns and heartbeats played consistently.

To bypass this under normal circumstances, either create a CCD/IMG/SUB dump with the subchannel data intact and untampered so that the game can load correctly, or use a PPF patch to patch out the LibCrypt protection, but as you already have created such tools, this has only been posted to inform you as to how the protection gets triggered and how it exhibits itself to the end-user.

**Comment by alex-free** [comment]
> Hello there
> 
> I am not sure where to post this as this is my first time contributing to adding in information to a project here, but I would like to let you know that This Is Football's LibCrypt protection kicks in whenever you try to load in a game with two teams selected, whereby the loading bar gets stuck at approximately 80-85%.
> 
> Also, V-Rally: Championship Edition 2 has the same protection with similar effects where if you try to choose your car and game mode, the game will try to load, and then permanently gets stuck on the loading screen with the ECG patterns and heartbeats played consistently.
> 
> To bypass this under normal circumstances, either create a CCD/IMG/SUB dump with the subchannel data intact and untampered so that the game can load correctly, or use a PPF patch to patch out the LibCrypt protection, but as you already have created such tools, this has only been posted to inform you as to how the protection gets triggered and how it exhibits itself to the end-user.

As specified in https://github.com/alex-free/tonyhax/blob/master/anti-piracy-bypass.md both these games suggest using the [LibCrypt Partcher](https://alex-free.github.io/libcrypt-patcher) I have developed. Both games are explicitly supported by the patcher :) let me know what you think...

I'd like to get tonyhax international bypassing libcrypt, but I am unsure how and when I will implement that functionallity.

![thisisfootball](https://github.com/alex-free/tonyhax/assets/72545918/d054dfb8-b079-47ab-a7d6-fcdf21fcbf9d)
![vralley](https://github.com/alex-free/tonyhax/assets/72545918/58aa4e0e-ccbd-4cab-a20a-9ec0fd309ec1)

**Comment by alex-free** [comment]
thankyou, added this info to https://github.com/alex-free/tonyhax/blob/master/anti-piracy-bypass.md . If you know of more libcrypt effects I can add to further complete the document, open a new issue.
