### ISSUE TITLE
Memcard Pro 2 Not Working With Game ID

### ISSUE THREAD

**Issue by CODJointOps** [alex-free/tonyhax#66]
Hello! On the latest version of tonyhax Game ID with the Memcard Pro 2 doesn't seem to be working for me at all. From the log when I bootup the game I get "MCPRO/SD2PSX detected in slot one" then on my memcard it displays "Loading" for a second but doesn't actually switch to a new VMC it just returns to the previous memcard it was on. Is there anything I could be doing wrong?

Info
Console model: SCPH-7501
BIOS version: 12/16/97 A
Entry point: Freepsxboot with Memcard Pro 2

**Comment by alex-free** [comment]
@lzibeti @CODJointOps please try this beta and get back to me
[tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)

**Comment by CODJointOps** [comment]
> @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)

This build sadly did not fix the issue, same issue occurs.

**Comment by CODJointOps** [comment]
> > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > 
> > 
> > This build sadly did not fix the issue, same issue occurs.
> 
> Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)

Still facing the same issue with this build

**Comment by alex-free** [comment]
> > > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > > 
> > > 
> > > This build sadly did not fix the issue, same issue occurs.
> > 
> > 
> > Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)
> 
> Still facing the same issue with this build

Please try this build
[tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017803/tonyhax-international-v1.5.4b6.zip)

**Comment by alex-free** [comment]
Another thing we can try:
[tonyhax-international-v1.5.4b7.zip](https://github.com/user-attachments/files/17017874/tonyhax-international-v1.5.4b7.zip)

**Comment by CODJointOps** [comment]
> > > > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > > > 
> > > > 
> > > > This build sadly did not fix the issue, same issue occurs.
> > > 
> > > 
> > > Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)
> > 
> > 
> > Still facing the same issue with this build
> 
> Please try this build [tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017803/tonyhax-international-v1.5.4b6.zip)

This works!

**Comment by alex-free** [comment]
> > > > > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > > > > 
> > > > > 
> > > > > This build sadly did not fix the issue, same issue occurs.
> > > > 
> > > > 
> > > > Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)
> > > 
> > > 
> > > Still facing the same issue with this build
> > 
> > 
> > Please try this build [tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017803/tonyhax-international-v1.5.4b6.zip)
> 
> This works!

Sweet, let me know if beta 7 works as  well

**Comment by CODJointOps** [comment]
> > > > > > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > > > > > 
> > > > > > 
> > > > > > This build sadly did not fix the issue, same issue occurs.
> > > > > 
> > > > > 
> > > > > Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)
> > > > 
> > > > 
> > > > Still facing the same issue with this build
> > > 
> > > 
> > > Please try this build [tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017803/tonyhax-international-v1.5.4b6.zip)
> > 
> > 
> > This works!
> 
> Sweet, let me know if beta 7 works as well

Beta 7 also does work

**Comment by alex-free** [comment]
> > > > > > > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > > > > > > 
> > > > > > > 
> > > > > > > This build sadly did not fix the issue, same issue occurs.
> > > > > > 
> > > > > > 
> > > > > > Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)
> > > > > 
> > > > > 
> > > > > Still facing the same issue with this build
> > > > 
> > > > 
> > > > Please try this build [tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017803/tonyhax-international-v1.5.4b6.zip)
> > > 
> > > 
> > > This works!
> > 
> > 
> > Sweet, let me know if beta 7 works as well
> 
> Beta 7 also does work

Last test if this goes well, really appreciate yall
[tonyhax-international-v1.5.4b8.zip](https://github.com/user-attachments/files/17018031/tonyhax-international-v1.5.4b8.zip)

**Comment by CODJointOps** [comment]
> > > > > > > > > @lzibeti @CODJointOps please try this beta and get back to me [tonyhax-international-v1.5.4b4.zip](https://github.com/user-attachments/files/17008677/tonyhax-international-v1.5.4b4.zip)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This build sadly did not fix the issue, same issue occurs.
> > > > > > > 
> > > > > > > 
> > > > > > > Lets try this [tonyhax-international-v1.5.4b5.zip](https://github.com/user-attachments/files/17017609/tonyhax-international-v1.5.4b5.zip)
> > > > > > 
> > > > > > 
> > > > > > Still facing the same issue with this build
> > > > > 
> > > > > 
> > > > > Please try this build [tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017803/tonyhax-international-v1.5.4b6.zip)
> > > > 
> > > > 
> > > > This works!
> > > 
> > > 
> > > Sweet, let me know if beta 7 works as well
> > 
> > 
> > Beta 7 also does work
> 
> Last test if this goes well, really appreciate yall [tonyhax-international-v1.5.4b8.zip](https://github.com/user-attachments/files/17018031/tonyhax-international-v1.5.4b8.zip)

It works

**Comment by lzibeti** [comment]
Sorry for the delay, but I was only able to test the version now and apparently the final version 1.5.4 has already been released.

I ended up testing version 1.5.4b10 with MemCardPro, MemcardPro2, SD2PSX and PicoMemCard and they all worked correctly with the following games:

- Resident Evil - Director's Cut Dual Shock Edition (USA)
- Final Fantasy 9 CD1 (USA)
- Rockman 4 (JP)
- Kings Field (JP)
- Ridge Racer (JP)
- Kileak - The Blood (JP)

What caught my attention when using MemCardPro2 is how it shows on the display when loading PSX.EXE games (e.g. Ridge Racer). First it changes from TonyHax to the generic VMC (memorycard1) when "BOOT cdrom:PSX.EXE:1" appears and then when it reaches the line "Sending cdrom:SLPS.000.027:1 as GameID" it changes again to the VMU corresponding to the game.

**Comment by alex-free** [comment]
> Sorry for the delay, but I was only able to test the version now and apparently the final version 1.5.4 has already been released.
> 
> I ended up testing version 1.5.4b10 with MemCardPro, MemcardPro2, SD2PSX and PicoMemCard and they all worked correctly with the following games:
> 
>     * Resident Evil - Director's Cut Dual Shock Edition (USA)
> 
>     * Final Fantasy 9 CD1 (USA)
> 
>     * Rockman 4 (JP)
> 
>     * Kings Field (JP)
> 
>     * Ridge Racer (JP)
> 
>     * Kileak - The Blood (JP)
> 
> 
> What caught my attention when using MemCardPro2 is how it shows on the display when loading PSX.EXE games (e.g. Ridge Racer). First it changes from TonyHax to the generic VMC (memorycard1) when "BOOT cdrom:PSX.EXE:1" appears and then when it reaches the line "Sending cdrom:SLPS.000.027:1 as GameID" it changes again to the VMU corresponding to the game.

Thanks for further testing. What catches your attention is the intended behavior. The original danhans42 memcard pro tonyhax fork initially sent a blank game id "" after detecting a memcard pro, before sending the real proper game id. I think now however due to the timing code being correct in the latest Tonyhax International (essentially the same as 1.4.5b10), it is more obvious that it occurs.

If you are up for it, I would find it interesting to see if it is in fact necessary. That way it would go directly from Tonyhax to the vmu corresponding to the game. This would be indeed faster.

Here is a build that works in such a way. Thanks:
@lzibeti 
[tonyhax-international-v1.5.5b1.zip](https://github.com/user-attachments/files/17036735/tonyhax-international-v1.5.5b1.zip)

**Comment by lzibeti** [comment]
> Thanks for further testing. What catches your attention is the intended behavior. The original danhans42 memcard pro tonyhax fork initially sent a blank game id "" after detecting a memcard pro, before sending the real proper game id. I think now however due to the timing code being correct in the latest Tonyhax International (essentially the same as 1.4.5b10), it is more obvious that it occurs.
> 
> If you are up for it, I would find it interesting to see if it is in fact necessary. That way it would go directly from Tonyhax to the vmu corresponding to the game. This would be indeed faster.
> 
> Here is a build that works in such a way. Thanks: @lzibeti [tonyhax-international-v1.5.5b1.zip](https://github.com/user-attachments/files/17036735/tonyhax-international-v1.5.5b1.zip)

I just tested this version 1.5.5b1 and it worked without problems on MemCardPro, MemCardPro2, SD2PSX and PicoMemcard.

In the case of MemCardPro2 it no longer loads the generic VMC (memorycard1), it continues to display TonyHax's VMC until it reaches the line "Sending cdrom:SLPS.000.027:1 as GameID" and with that it creates/loads the game's VMC.

The games I tested were:
- Resident Evil - Director's Cut Dual Shock Edition (USA)
- Rockman 4 (JP)
- Kings Field (JP)
- Ridge Racer (JP)
- Kileak - The Blood (JP)

**Comment by alex-free** [comment]
> > Thanks for further testing. What catches your attention is the intended behavior. The original danhans42 memcard pro tonyhax fork initially sent a blank game id "" after detecting a memcard pro, before sending the real proper game id. I think now however due to the timing code being correct in the latest Tonyhax International (essentially the same as 1.4.5b10), it is more obvious that it occurs.
> > If you are up for it, I would find it interesting to see if it is in fact necessary. That way it would go directly from Tonyhax to the vmu corresponding to the game. This would be indeed faster.
> > Here is a build that works in such a way. Thanks: @lzibeti [tonyhax-international-v1.5.5b1.zip](https://github.com/user-attachments/files/17036735/tonyhax-international-v1.5.5b1.zip)
> 
> I just tested this version 1.5.5b1 and it worked without problems on MemCardPro, MemCardPro2, SD2PSX and PicoMemcard.
> 
> In the case of MemCardPro2 it no longer loads the generic VMC (memorycard1), it continues to display TonyHax's VMC until it reaches the line "Sending cdrom:SLPS.000.027:1 as GameID" and with that it creates/loads the game's VMC.
> 
> The games I tested were:
> 
>     * Resident Evil - Director's Cut Dual Shock Edition (USA)
> 
>     * Rockman 4 (JP)
> 
>     * Kings Field (JP)
> 
>     * Ridge Racer (JP)
> 
>     * Kileak - The Blood (JP)

That's great, this change will be out in v1.5.5. I'm not quite sure why the original danhans42 code did the blank gameid send on mcpro detection but your testing shows it is not required.
