### ISSUE TITLE
PSX.EXE GameID - Jumping Flash! (SCPS-10007) and Arc the Lad (SCPS-10008)

### ISSUE THREAD

**Issue by StevtheRPGGuy** [alex-free/tonyhax#67]
While testing the PSX.EXE GameID feature of Tonyhax International v1.5.3, I found that both Jumping Flash! and Arc the Lad cause the following message to be displayed: "Unknown PSX.EXE ID, unique GameID unavailable."

**Comment by alex-free** [comment]
Please try this build
[tonyhax-international-v1.5.4b6.zip](https://github.com/user-attachments/files/17017813/tonyhax-international-v1.5.4b6.zip)

**Comment by alex-free** [comment]
Heres another I'd like you to try, thanks
[tonyhax-international-v1.5.4b7.zip](https://github.com/user-attachments/files/17017897/tonyhax-international-v1.5.4b7.zip)

**Comment by alex-free** [comment]
One last test build
[tonyhax-international-v1.5.4b8.zip](https://github.com/user-attachments/files/17018035/tonyhax-international-v1.5.4b8.zip)

**Comment by StevtheRPGGuy** [comment]
In my testing, I found that although the two games are now recognized, PSX.EXE GameID no longer switches to a game specific VMC on my MemCard PRO 2, although SYSTEM.CNF GameID still works. On v1.5.3, I was able to use game specific VMCs for King's Field and Ridge Racer.

**Comment by alex-free** [comment]
> In my testing, I found that although the two games are now recognized, PSX.EXE GameID no longer switches to a game specific VMC on my MemCard PRO 2, although SYSTEM.CNF GameID still works. On v1.5.3, I was able to use game specific VMCs for King's Field and Ridge Racer.

Is this with beta 8? Would you mind taking a picture of what happens before the game starts?

**Comment by StevtheRPGGuy** [comment]
![IMG_20240916_132814282~2](https://github.com/user-attachments/assets/d46171eb-8161-45bf-9ad8-839c2e3a8525)

**Comment by StevtheRPGGuy** [comment]
After uploading it, I now realize how blurry that picture is. If it's necessary, I'll take another picture after moving the PlayStation to a different TV

**Comment by StevtheRPGGuy** [comment]
![IMG_20240916_135501946~2](https://github.com/user-attachments/assets/912b54cc-eec2-49d4-8332-c74b59269bcb)

**Comment by alex-free** [comment]
> ![IMG_20240916_135501946~2](https://private-user-images.githubusercontent.com/107147161/367912397-912b54cc-eec2-49d4-8332-c74b59269bcb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTgxMjIsIm5iZiI6MTcyNjUxNzgyMiwicGF0aCI6Ii8xMDcxNDcxNjEvMzY3OTEyMzk3LTkxMmI1NGNjLWVlYzItNDlkNC04MzMyLWM3NGI1OTI2OWJjYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQyMDE3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDhhY2JhZjI2YTRkNDk2NDkxMmNlYzhjYjk4MTBiNmRhMDNmMjEwMjU1ZjE3NGNhNjY5YTlmOTZlYzNiMjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WN8lllFhHDZLObw9I7x3ZXue7jvpuorsG_bshqqj2PE)

Please try this
[tonyhax-international-v1.5.4b9.zip](https://github.com/user-attachments/files/17019468/tonyhax-international-v1.5.4b9.zip)

**Comment by StevtheRPGGuy** [comment]
I'm still not having any luck. When the "Sending cdrom:????_???.??;1 as GameID" message appears, the MemCard PRO 2 screen does show the "Loading..." message as it normally does when it receives the GameID.

**Comment by StevtheRPGGuy** [comment]
After that, it just uses the default VMC.

**Comment by alex-free** [comment]
> After that, it just uses the default VMC. 

Are you using the mcpro for FreePSXBoot?

**Comment by StevtheRPGGuy** [comment]
Yes

**Comment by alex-free** [comment]
> Yes

But system.cnf games do send the game id correctly?

**Comment by StevtheRPGGuy** [comment]
After testing two SYSTEM.CNF games, they do send the GameID correctly

**Comment by alex-free** [comment]
> After testing two SYSTEM.CNF games, they do send the GameID correctly

Thanks for the reports, I think this should work correctly now
[tonyhax-international-v1.5.4b10.zip](https://github.com/user-attachments/files/17021140/tonyhax-international-v1.5.4b10.zip)

**Comment by StevtheRPGGuy** [comment]
All four PSX.EXE games I tested now correctly send GameID, and SYSTEM.CNF games continue to correctly send GameID.

**Comment by alex-free** [comment]
> All four PSX.EXE games I tested now correctly send GameID, and SYSTEM.CNF games continue to correctly send GameID.

Nice. I'll release v1.5.4 pretty soon.

**Comment by alex-free** [comment]
Fixed in v1.5.4 :)
