### ISSUE TITLE
2 games in GameID using same timestamp

### ISSUE THREAD

**Issue by sh06un** [alex-free/tonyhax#68]
https://github.com/alex-free/tonyhax/blob/1d1f1cc74fe000b560d93506b9fd98e9da81203f/loader/gameid-psx-exe.c#L432

https://github.com/alex-free/tonyhax/blob/1d1f1cc74fe000b560d93506b9fd98e9da81203f/loader/gameid-psx-exe.c#L437

I was just checking this out, purely out of curiosity, and saw that these 2 cases that I've linked above both use the same number for the timestamp checking. Is this a bug?

**Comment by alex-free** [comment]
Thank you, this was a bug I fixed it so that Eisei Meijin (Japan) (Rev 1) is now detected correctly:
https://github.com/alex-free/tonyhax/blob/49737f93e0529cbfde884028a54caf8ec1fe6e2e/loader/gameid-psx-exe.c#L439

**Comment by sh06un** [comment]
No worries, glad that's another one squashed!! And thanks for the shoutout on the release.
