### ISSUE TITLE
Memcard Pro 2 not working with newest update

### ISSUE THREAD

**Issue by Fallenspirit** [alex-free/tonyhax#70]
Game ID has not worked with my Memcard Pro 2 since 1.5.6. I just installed the 1.5.8 update and it still does not send any game info to the memory card. It worked great on 1.5.5

**Comment by kimbapslice** [comment]
What's your setup like? Are you running tonyhax int from a cartridge or from the memcard pro 2? Firmware? Ps1 model? etc.
Also, can you post a screenshot of your mcpro2 settings? I think both my mcpro1 and mcpro2 worked fine but I will double check later after work. Thanks!

**Comment by Fallenspirit** [comment]
I completely apologize. I believe I just needed to update my Memcard Pro 2. It's working correctly again.

**Comment by kimbapslice** [comment]
Glad you got it working.

**Comment by alex-free** [comment]
@Fallenspirit was this just the index.txt needing editing as per https://github.com/alex-free/tonyhax/blob/master/changelog.md#version-156-1062024 ? Or was this some kind of memcardpro firmware thing?

**Comment by Fallenspirit** [comment]
No, I do not have any of the titles that had issues before. I was using my real Resident Evil Directors Cut and Tomb Raider discs as tests. Both worked completely fine up to 1.5.5. For some reason, for 1.5.6-1.5.8 it wouldn't work at all. It would remain on the generic memory card that's auto created. When I ran the MemcardPro 2 update via the wifi connection, it fixed the issues and worked correctly again.

**Comment by alex-free** [comment]
> No, I do not have any of the titles that had issues before. I was using my real Resident Evil Directors Cut and Tomb Raider discs as tests. Both worked completely fine up to 1.5.5. For some reason, for 1.5.6-1.5.8 it wouldn't work at all. It would remain on the generic memory card that's auto created. When I ran the MemcardPro 2 update via the wifi connection, it fixed the issues and worked correctly again. 

Great, nothing on my end (for now).
