### ISSUE TITLE
Blocked game -  not listed

### ISSUE THREAD

**Issue by ps1vault** [alex-free/tonyhax#72]
**tonyhax version **: 1.5.8
**Game name**: GeGeGe no Kitarou Gyakushuu! Youma Daikessen
**Game code**: SLPM-87342
**Executable hash**: GeGeGe no Kitarou - Gyakushuu! Youma Daikessen (Japan).bin
Crc
0c5ece5b
Md5
b52cd0642c87150c2df41fff33945e0e
Sha1
ff7bdfa9adff33289cfe5ebd36149161235c4224

GeGeGe no Kitarou - Gyakushuu! Youma Daikessen (Japan).cue
Crc
cd9d91c1
Md5
87caee97bca92752cff55f7a301a662a
Sha1
b4c3bedbe25d565868a0cce1fa9e9e10a339b94d
**Triggered at**: After the KONAMI logo screen
**Is it an original disc or a burned copy?**: Burned CD-R. 

This is now one of the most expensive PS1 games to own. It was one of the last games released on the console in 2003. There aren't many copies so almost everyone will be playing CDR or on import. It's a reallly great bossrush/platform game based on the famous Manga. 

Many thanks if you could support this classic game!

**Comment by ps1vault** [comment]
any updates on this, any chance it will get fixed? Thanks for your work.

**Comment by alex-free** [comment]
> any updates on this, any chance it will get fixed? Thanks for your work.

Please try this beta 
[tonyhax-international-v1.5.9b1.zip](https://github.com/user-attachments/files/17865602/tonyhax-international-v1.5.9b1.zip)

**Comment by ps1vault** [comment]
> > any updates on this, any chance it will get fixed? Thanks for your work.
> 
> Please try this beta [tonyhax-international-v1.5.9b1.zip](https://github.com/user-attachments/files/17865602/tonyhax-international-v1.5.9b1.zip)

Yes! It worked! So happy. Thank you Alex for this, you are, a legend.

**Comment by alex-free** [comment]
> > > any updates on this, any chance it will get fixed? Thanks for your work.
> > 
> > 
> > Please try this beta [tonyhax-international-v1.5.9b1.zip](https://github.com/user-attachments/files/17865602/tonyhax-international-v1.5.9b1.zip)
> 
> Yes! It worked! So happy. Thank you Alex for this, you are, a legend.

aprip for the win. This will be v1.5.9, I'll push it now

**Comment by alex-free** [comment]
Supported in v1.5.9
